Gemfile, Gemfile.lock, config/initializers/devise.rb, config/locales/devise.en.yml
Added devise gem in gemfile,
Initialized devise gem in config
=> Added devise gem

app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, config/routes.rb, db/migrate/20221115081115_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
Added user model using the devise gem.
-generated user views
=> Added user model

app/models/artwork.rb, app/models/offer.rb, app/models/user.rb, db/migrate/20221115082424_create_artworks.rb, db/migrate/20221115083801_rename_foreign_key.rb, db/migrate/20221115084526_create_offers.rb, db/migrate/20221115085023_rename_user_foreign_key.rb, db/schema.rb, test/models/artwork_test.rb, test/models/offer_test.rb
Add models
-Offer with valids & assocs
-Artwork with valids & assocs
Misc
-null: false in migrations
-changed name in foreign keys for clearer reference
=> Add models

Gemfile.lock, app/controllers/artworks_controller.rb, app/views/devise/sessions/new.html.erb
Syntax issue on devise - sessions - new.html.erb
Signup and login pages now working
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> fixed typo on sessions new

app/views/layouts/application.html.erb, app/views/pages/home.html.erb, config/environments/development.rb
-Edited config in dev.rb
-Added alerts in app.html.rb
-Added user links in default home-page
Tested links in local server.
=> Edited config in dev.rb && added alerts in app.html.rb && added session links for testing

db/migrate/20221116025926_add_name_surnameto_users.rb, db/schema.rb
Background : There is no user name and surname currently in the schema for users
What I did: 
- I added a migration to add user_name and last_name to the schema 
- with null false
=> added name surname to users model

app/controllers/artworks_controller.rb, app/models/artwork.rb, app/views/artworks/index.html.erb, app/views/artworks/new.html.erb, app/views/artworks/show.html.erb, config/routes.rb
Edited artworks.controller actions for new, create, show, index, destroy and created views for artworks.
Tested locally and confirmed it works
=> Artworks controller and views except edit

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/devise/shared/_navbar.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
Created navbar partial with custom styling. Can be used with render for individual pages
-buttons.scss
-navbar.scss
=> Add navbar

db/migrate/20221116052853_remove_first_and_last_name.rb, db/schema.rb
-removed first and last name columns, intend to add back in a later migration (Wrong data types)
=> remove first & last name columns from users table

app/controllers/offers_controller.rb, app/views/offers/index.html.erb, app/views/offers/new.html.erb, app/views/offers/show.html.erb, config/routes.rb, test/controllers/offers_controller_test.rb
Created orders controller
-views
-routes
=> Created offers controller

app/controllers/offers_controller.rb, app/views/artworks/show.html.erb, app/views/offers/index.html.erb, app/views/offers/new.html.erb, app/views/offers/show.html.erb, config/routes.rb, test/controllers/offers_controller_test.rb
- edited offer routes to nest certain actions
- created new and create methods
- created make offer button in artwork#show
=> Feature add offer#new offer#create

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_icard.scss, app/assets/stylesheets/components/_index.scss, app/views/artworks/index.html.erb, app/views/artworks/show.html.erb, app/views/devise/shared/_footer.html.erb
Artworks:
- created show page
- created index page to view all artworks
- created footer which is a partial
**Outstanding**
- when seeding of db artworks is done ensure the iterations of @artworks.each do displays individual art
=> show, index and footer front end

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_link.scss, app/controllers/offers_controller.rb, app/views/devise/shared/_navbar.html.erb, app/views/offers/index.html.erb
- added offers#index method for buyer’s offers
- added styling on view
- added link.scss component
- added ref link to offer.artwork
- fix delete button styling
=> Created offers#index

Gemfile, Gemfile.lock, db/seeds.rb
I have created a seeds file that generates 
- 5 Users
- 20 Artworks
E.g. Users created by seed file:
<User id: 614, email: "ellsworth@example.net", created_at: "2022-11-16 09:51:12.242723000 +0000", updated_at: "2022-11-16 09:51:12.242723000 +0000", first_name: "Lia", last_name: "Littel">,
E.g Artwork created by seed file:
#<Artwork:0x000000010a306b90                                      
id: 18,                                                          
artist_name: "Durer",                                            
title: "Command & Conquer: Red Alert 3",                         
theme: "Real-time strategy",                                     
year: 1704,                                                      
price: 8207581,                                                  
details: …
=> Seeding users

app/assets/stylesheets/components/_icard.scss, app/views/artworks/index.html.erb, app/views/pages/home.html.erb, db/seeds.rb
- seeded DB with artworks and users
- updated row with auto cols and wrapping
- wrapped cards in col div
- artworks list following placeholder format
- alignment change in container from center to flex-start
- fixed typo in seeds.rb to be a String instead
=> Updated view to include artworks from seed

app/assets/stylesheets/components/_footer.scss, app/views/artworks/extra.html.erb, app/views/artworks/show.html.erb, app/views/devise/shared/_footer.html.erb
Footer as a partial (both HTML and SCSS) fixed so can render these to the individual pages as needed
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] local server
=> fixed styling for the footer

app/controllers/artworks_controller.rb, app/views/artworks/index.html.erb, app/views/artworks/show.html.erb, app/views/pages/home.html.erb, config/routes.rb
Link to "Sell"
-route points to users/:id/artworks with params[:user_id]
-artworks index now can take a signed_in? condition, where user will be directed to index.html with seller's artworks
-WIP: To be used in navbar && additional logic needed to filter logged-in buyers from sellers?
=> Addedlink to view seller artworks on homepage

app/controllers/pages_controller.rb, app/views/artworks/index.html.erb, app/views/devise/shared/_navbar.html.erb, app/views/offers/new.html.erb, app/views/pages/home.html.erb
=> home styling fix

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/controllers/application_controller.rb, app/views/artworks/show.html.erb, app/views/offers/new.html.erb
1/ Added store_user_location and storable_location to send a user to the current page after sign-in 
2/ Fixed new page for i) button style and ii) height adjustment 
(deleted .showbutton css line from _buttonn.css as it's no longer needed / adjusted height of .card-product)  
- [ x] local server
=> Fixing after_sign_in logic and new page 

app/controllers/offers_controller.rb, app/views/offers/index.html.erb, app/views/offers/show.html.erb, app/views/pages/home.html.erb, config/routes.rb
Added quick links to get to the offers pages and links to the individual offers from the offers table
Missing styling for now.
- [ x] rails console
- [x ] local server
=> added links to offers - no styling

app/controllers/artworks_controller.rb, app/views/artworks/index.html.erb
Artwork submission not relating to the right owner of the artwork and therefore not displaying to owners artworks panel.
=> fixed issue submitting artwork to right owner

app/assets/stylesheets/components/_card.scss, app/views/artworks/index.html.erb
Re-did styling of artworks index - more similar to Artsy.
Pending:
- ensure uploaded images deliver masonry effect and correlate the image to the right artwork
- [ x] local server
=> fixed styling of artworks

app/controllers/offers_controller.rb, app/models/offer.rb, app/views/artworks/index.html.erb, app/views/artworks/show.html.erb, app/views/devise/shared/_navbar.html.erb, app/views/offers/index.html.erb, config/routes.rb, db/migrate/20221118031750_add_status_column.rb, db/schema.rb, db/seeds.rb
- add status column to offers table
- added validations
- updated make offer link to appear if viewing artwork as a buyer
- updated offers link to appear if viewing artwork as a seller
- updated offers index to show all offers if buyer, and artwork offers if seller
- added offers I’ve received link on seller artwork index
- fixed bootstrap styling on all buttons to outline
- updated offers index to show offers for all artworks if seller clicks on offers i’ve received 
- create accept button that changes status of offer to accepted, and changes the rest of the offers to rejected, which only shows if offer is pending
=> Added feature to accept and reject offers

db/schema.rb, db/seeds.rb
Updated seeds.rb to include validation for theme
=> Updated seed file

app/views/artworks/index.html.erb, db/seeds.rb
- I have changed the seed file so that pictures are uploaded for every artwork seed item.
- I have changed the /artworks file to reflect the seeded images
=> seed file now generates artwork and is reflected on the /artworks page

app/controllers/offers_controller.rb, app/views/artworks/index.html.erb, app/views/pages/home.html.erb, db/seeds.rb
- remove placeholder for images on homepage
- update seed file to remove randomised users for easy testing
- users now include: YOUR_NAME@gmail.com
=> Bugfix remove placeholder homepage

app/controllers/offers_controller.rb
Added "pending" to offer.status at point of creation, to allow offer to be saved
=> Fixed offer create bug, added default status of pending

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_header.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/artworks/index.html.erb, app/views/devise/shared/_carousel2.html.erb, app/views/devise/shared/_footer.html.erb, app/views/devise/shared/_navbar.html.erb, app/views/pages/home.html.erb
Styling edits for
-   artwork index
- added header row
- footer
- artworks list 
- homepage
- carousel
=> Edited Styling

.gitignore, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_carousel.scss, app/views/artworks/index.html.erb, app/views/devise/shared/_carousel.html.erb
Please include a summary of the change and/or which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixed styling on carousel
=> more carouself styling

db/seeds.rb
Duplicate seed images generated on production but not on development. The likely cause is that the production server makes image requests in a close interval - such that the same image has not had a chance to update, and so the same image is downloaded on two API calls. 
Code has been amended to require an unique image to be generated for each call request: Previous code:
"file = URI.open("https://source.unsplash.com/random"
Proposed change
"file = URI.open("https://source.unsplash.com/random?sig=#{rand(1000..100000000)}")"
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] local server
=> Refactor seeds and fix unsplash bug

.gitignore, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_navbar.scss, app/models/artwork.rb, app/views/artworks/new.html.erb, app/views/artworks/show.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_footer.html.erb, app/views/offers/new.html.erb
- Updated formatting for artwork's new, offer and artwork new forms, and updated border setting for navbar and footer
- Added price_delimit function to Artwork to show price with thousand separator commas 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] rails console
- [x ] local server
=> Price delimit & front end changes 

app/controllers/artworks_controller.rb, app/views/artworks/index.html.erb
- removed duplicate code on artworks index
- added header for search results page
=> removed duplicate code

app/assets/stylesheets/components/_form.scss, app/controllers/offers_controller.rb, app/models/offer.rb, app/views/artworks/index.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/offers/index.html.erb, app/views/offers/show.html.erb, app/views/pages/home.html.erb
Changes to offer and sign-in forms 
- [x ] New feature (non-breaking change which adds functionality)
- [ x] rails console
- [ x] local server
=> sign in and session forms and offer pages

app/views/artworks/index.html.erb, app/views/devise/shared/_carousel2.html.erb, app/views/offers/index.html.erb, app/views/pages/home.html.erb
Made some minor front end changes to index show and home html 
- [ x] Bug fix (non-breaking change which fixes an issue)
=> Minor frontend
